stages:
  - build
  - test
  - deploy

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build_job:
  stage: build
  image: openjdk:17-jdk
  before_script:
    - chmod +x gradlew
  script:
    - ./gradlew assembleDebug
  cache:
    key: gradle
    paths:
      - ~/.gradle/wrapper
      - ~/.gradle/caches
  artifacts:
    paths:
      - app/build/outputs/apk/debug/app-debug.apk
    expire_in: 1 week
  only:
    - main
    - develop
    - merge_requests

test_job:
  stage: test
  image: openjdk:17-jdk
  before_script:
    - chmod +x gradlew
  script:
    - ./gradlew testDebugUnitTest
  cache:
    key: gradle
    paths:
      - ~/.gradle/wrapper
      - ~/.gradle/caches
  artifacts:
    paths:
      - app/build/reports/tests/
    expire_in: 1 week
  only:
    - main
    - develop
    - merge_requests

code_quality_job:
  stage: test
  image: openjdk:17-jdk
  before_script:
    - chmod +x gradlew
  script:
    - ./gradlew ktlintCheck
    - ./gradlew detekt
    - ./gradlew lintDebug
  cache:
    key: gradle
    paths:
      - ~/.gradle/wrapper
      - ~/.gradle/caches
  artifacts:
    paths:
      - app/build/reports/lint-results-debug.html
      - build/reports/detekt/
    expire_in: 1 week
  only:
    - main
    - develop
    - merge_requests

dependency_check:
  stage: test
  image: openjdk:17-jdk
  before_script:
    - chmod +x gradlew
  script:
    - ./gradlew dependencyUpdates
    - ./gradlew dependencyUpdates -DoutputFormatter=json -DoutputDir=build/dependencyUpdates
  cache:
    key: gradle
    paths:
      - ~/.gradle/wrapper
      - ~/.gradle/caches
  artifacts:
    paths:
      - build/dependencyUpdates/
    expire_in: 1 week
  only:
    - schedules
    - web

comment_dependency:
  stage: test
  image: openjdk:17-jdk
  before_script:
    - chmod +x gradlew
  script:
    - chmod +x gradlew
    - ./gradlew assembleDebug
    - ./gradlew testDebugUnitTest
  cache:
    key: gradle
    paths:
      - ~/.gradle/wrapper
      - ~/.gradle/caches
  artifacts:
    paths:
      - app/build/outputs/apk/debug/app-debug.apk
      - app/build/reports/tests/
    expire_in: 1 week
  only:
    - merge_requests
    paths:
      - build/dependencyUpdates/
    expire_in: 1 week
  only:
    - merge_requests

release_job:
  stage: deploy
  image: openjdk:17-jdk
  before_script:
    - chmod +x gradlew
  script:
    - ./gradlew assembleRelease
    - ./gradlew bundleRelease
  cache:
    key: gradle
    paths:
      - ~/.gradle/wrapper
      - ~/.gradle/caches
  artifacts:
    paths:
      - app/build/outputs/apk/release/app-release.apk
      - app/build/outputs/bundle/release/app-release.aab
    expire_in: 1 month
  release:
    name: "Release $CI_COMMIT_TAG"
    description: "Release notes for $CI_COMMIT_TAG"
    tag_name: "$CI_COMMIT_TAG"
    assets:
      links:
        - name: "AutoReplyMessenger-$CI_COMMIT_TAG.apk"
          url: "$CI_PROJECT_URL/-/jobs/$CI_JOB_ID/artifacts/file/app/build/outputs/apk/release/app-release.apk"
        - name: "AutoReplyMessenger-$CI_COMMIT_TAG.aab"
          url: "$CI_PROJECT_URL/-/jobs/$CI_JOB_ID/artifacts/file/app/build/outputs/bundle/release/app-release.aab"
  only:
    - tags

manual_release:
  stage: deploy
  image: openjdk:17-jdk
  before_script:
    - chmod +x gradlew
  script:
    - ./gradlew assembleRelease
    - ./gradlew bundleRelease
  cache:
    key: gradle
    paths:
      - ~/.gradle/wrapper
      - ~/.gradle/caches
  artifacts:
    paths:
      - app/build/outputs/apk/release/app-release.apk
      - app/build/outputs/bundle/release/app-release.aab
    expire_in: 1 month
  when: manual
  except:
    - tags
